config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'users/index'

  resources :movies
  root 'movies#index'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users











end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :movie
	belongs_to :user
	

end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  	helper_method :current_user 

	def current_user 
  		@current_user ||= User.find(session[:user_id]) if session[:user_id] 
	end
	
	helper_method :require_user
	def require_user 
  		redirect_to '/login' unless current_user 
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_comment, only: [:show, :edit, :update, :destroy]


  # GET /comments

  # GET /comments.json
 
 def index

    @comments = Comment.all

  end


  # GET /comments/1

  # GET /comments/1.json

  def show

  end


  # GET /comments/new
  def new

    @comment = Comment.new

  end


  # GET /comments/1/edit

  def edit

  end


  # POST /comments

  # POST /comments.json

  def create

    @comment = Comment.new(comment_params)


	@comment.user_name = current_user.first_name
	
    respond_to do |format|

      if @comment.save

        format.html { redirect_to :back, notice: 'Comment was successfully created.' }

        format.json { render :show, status: :created, location: @comment }

	
      else

        format.html { render :new }

        format.json { render json: @comment.errors, status: :unprocessable_entity }

      end

    end

  end


  # PATCH/PUT /comments/1

  # PATCH/PUT /comments/1.json

  def update

    respond_to do |format|

      if @comment.update(comment_params)

        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }

        format.json { render :show, status: :ok, location: @comment }

      else

        format.html { render :edit }

        format.json { render json: @comment.errors, status: :unprocessable_entity }

      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json

  def destroy
    @comment.destroy
    respond_to do |format|

      format.html { redirect_to :back, notice: 'Comment was successfully destroyed.' }

      format.json { head :no_content }

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_name, :body, :movie_id)
    end
end


app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.order(params[:sort])
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
	@comments = @movie.comments.all
	@comment = @movie.comments.build
  end

  # GET /movies/new
  
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        flash[:success] = 'Movie was successfully created.'
        format.html { redirect_to @movie }
        format.json { render :show, status: :created, location: @movie }
      else
        flash[:danger] = 'There was a problem creating the Movie.'
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        flash[:success] = 'Movie was successfully updated.'
        format.html { redirect_to @movie }
        format.json { render :show, status: :ok, location: @movie }
      else
        flash[:danger] = 'There was a problem updating the Movie.'
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      flash[:success] = 'Movie was successfully deleted.'
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :review, :year, :image, :genre, :synopsis)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end
	def create
  		@user = User.find_by_email(params[:sessions][:email])
  		if @user && @user.authenticate(params[:sessions][:password])
    			session[:user_id] = @user.id
    			redirect_to ''
  		else
    			redirect_to 'login'
  		end 
	end
	def destroy
		session[:user_id] = nil
		redirect_to ''
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
	@user = User.new
  end

  def create
  @user = User.new(user_params)
  if @user.save
	session[:user_id] = @user.id
	redirect_to '/'
  else
	redirect_to '/signup'
  end
  end
  private
  def user_params
	params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>

  <% if @comment.errors.any? %>

    <div id="error_explanation">

      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>


      <ul>

      <% @comment.errors.full_messages.each do |message| %>

        <li><%= message %></li>

      <% end %>

      </ul>

    </div>

  <% end %>


<%= f.hidden_field :user_name %> 
  <div class="field">

    <%= f.label :body %><br>

    <%= f.text_area :body %>

  </div>

	<%= f.hidden_field :movie_id %>
  
  <div class="actions">

    <%= f.submit %>

  </div>

<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice">
<%= notice %>
</p>

<h1>Listing Comments</h1>

<table>

  <thead>

    <tr>

      <th>User name</th>

      <th>Body</th>

      <th>Movie</th>

      <th colspan="3"></th>

    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.movie_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>


<%= f.hidden_field :user_name, :value => current_user.first_name %> 
<%= render 'form' %>


<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>


<p>

  <strong>User name:</strong>

  <%= @comment.user_name %>

</p>


<p>

  <strong>Body:</strong>

  <%= @comment.body %>
</p>


<p>

  <strong>Movie:</strong>

  <%= @comment.movie_id %>

</p>


<%= link_to 'Edit', edit_comment_path(@comment) %>
 |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!-- app/views/layouts/application.html.erb -->

<!DOCTYPE html>
<html>
<script type="text/javascript" src="heartRatingScript.js"></script>
  <head>
    <title>MovieDrive</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  
   <style type="text/css">

     body {background-color: #ff69b4; 
     }

/* #####################HTML for SEARCH BAR APPEARANCE ########################*/
	#tfnewsearch{
		float:left;
		padding:0px 65px;
	}

	.tftextinput{
		margin: 0;
		padding: 5px 15px;
		font-family: Arial, Helvetica, sans-serif;
		font-size:14px; /*Size of the search font*/
	}
	.tfbutton {
		margin: 0;
		padding: 5px 15px;
		font-family: Arial, Helvetica, sans-serif;
		font-size:14px;
		outline: none;
		cursor: pointer;
		text-align: center;
		text-decoration: none;
		color: #ffffff;
		border: solid 1px #800080; /*Border color of the search button*/
		background: #000000;
		border-top-right-radius: 5px 5px;
		border-bottom-right-radius: 5px 5px;
	}
	.tfbutton:hover {
		text-decoration: none;
		background: #800080;
	}
	/* Fixes submit button height problem in Firefox */
	.tfbutton::-moz-focus-inner {
	  border: 0;
	}
	.tfclear{
		clear:both;
	}
/* ############################################################################*/

</style>
</head>

    <%= render 'shared/navigation' %>
  
<body>
    <!-- ################### HTML for SEARCH BAR FUNCTIONALITY ###################-->
	<div id="tfheader">
		<form id="tfnewsearch" method="get" action="http://www.google.com">
		        <input type="text" class="tftextinput" name="q" size="21" maxlength="120"><input type="submit" value="search" class="tfbutton">
		</form>
	<div class="tfclear"></div>
	</div>
<!-- #########################################################################-->

    <div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-12">
          <% flash.each do |name, msg| -%>
            <%= content_tag :div, msg, class: "alert alert-#{name}" %>
          <% end -%>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-23">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<!-- app/views/movies/_form.html.erb -->

    <div class="well" id="movieSection">
    <div class="starter-template">

<%= form_for(@movie, html: {class: 'form-horizontal'}) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :review, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :review, class: 'form-control' %>
    </div>
  </div>
  
  <div class="field form-group">
    <%= f.label :image, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :image, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :year, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :year, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :genre, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :genre, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :synopsis, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :synopsis, class: 'form-control' %>
    </div>
  </div>

  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<!-- app/views/movies/index.html.erb -->
<script type="text/javascript" src="assets\heartRatingScript.js"></script>
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

    <div class="well" id="movieSection">
    <div class="starter-template">

<table>
  <thead>
    <tr>
	<th class="col-md-1"></th>
      <th class="col-md-2"><%= link_to "Title", :sort => "title" %></th>
      <th><%= link_to "Review", :sort => "review" %></th>
      <th class="col-md-1"><%= link_to "Year", :sort => "year" %></th>
      <th><%= link_to "Genre", :sort => "genre" %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody onload="toHearts()">
    <% @movies.each do |movie| %>
      <tr>
	<td class="col-md-2"><%= image_tag(movie.image, size: "90x120") %></td>
        <td class="col-md-2"><%= movie.title %></td>
        <td class="rating">

	<% if movie.review == 1 %>
		<%= image_tag("1tree.png") %>
	<% end %>
	<% if movie.review == 2 %>
		<%= image_tag("2tree.png") %>
	<% end %>
	<% if movie.review == 3 %>
		<%= image_tag("3tree.png") %>
	<% end %>
	<% if movie.review == 4 %>
		<%= image_tag("4tree.png") %>
	<% end %>
	<% if movie.review == 5 %>
		<%= image_tag("5tree.png") %>
	<% end %>

	</td>
        <td class="col-md-1"><%= movie.year %></td>
        <td><%= movie.genre %></td>
        <td><%= link_to 'Show', movie, class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie), class: 'btn btn-info btn-xs' %></td>
        <td><%= link_to 'Delete', movie, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>



app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<script type="text/javascript" src="heartRatingScript.js"></script>
<div class="well" id="movieSection">
	<div class="starter-template">
	<div class="row">
		<div class="col-md-4">
			<p>
				<%= image_tag(@movie.image, :size => "300x500") %> 
			</p>
		</div>

		<div class="col-md-8" onload="toHearts()">
			<p id="notice">
			<%= notice %>
			</p>



			<p>
 		 	<strong>Title:</strong>
 		 	<%= @movie.title %>
			</p>

			<p class="rating">
 			 <strong>Review:</strong>
	<% if @movie.review == 1 %>
		<%= image_tag("1tree.png") %>
	<% end %>
	<% if @movie.review == 2 %>
		<%= image_tag("2tree.png") %>
	<% end %>
	<% if @movie.review == 3 %>
		<%= image_tag("3tree.png") %>
	<% end %>
	<% if @movie.review == 4 %>
		<%= image_tag("4tree.png") %>
	<% end %>
	<% if @movie.review == 5 %>
		<%= image_tag("5tree.png") %>
	<% end %>
			</p>

			<p>
  			<strong>Year:</strong>
  			<%= @movie.year %>
			</p>

			<p>
  			<strong>Genre:</strong>
  			<%= @movie.genre %>
			</p>

			<p>
  			<strong>Synopsis:</strong>
  			<%= @movie.synopsis %>
			</p>
			<body >
			<h3><strong>Comments</strong></h3>
				<% @comments.each do |comment| %>
  			<div>
    				<strong><%= comment.user_name %></strong>
    				<br />
    				<p><%= comment.body %></p>
    				<p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
  			</div>
			<% end %>
			<%= render 'comments/form' %>
			</body>
		</div>
	
	</div>
	</div>
<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>



</div>

app/views/shared/_navigation.html.erb
<!-- app/views/shared/_navigation.html.erb -->

<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">MovieDrive</a>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">

<% if current_user %> 
    <li><%= current_user.email %></li> 
    <li><%= link_to "Log out", logout_path, method: "delete" %></li> 
<% else %> 
    <li><%= link_to "Login", 'login' %></a></li> 
    <li><%= link_to "Signup", 'signup' %></a></li> 
<% end %>

          <li class="divider"></li>
          <li><%= link_to 'Create a movie', new_movie_path %></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

app/views/users/new.html.erb
<div class="well" id="movieSection">
<div class="starter-template">

<div class="login">

  <div class="container">
    <div class="form">

    <h1>Create Account</h1>

    <%= form_for(@user) do |f| %>
      <%= f.text_field :first_name, :placeholder => "First name" %>
      <%= f.text_field :last_name, :placeholder => "Last name" %>
      <%= f.email_field :email, :placeholder => "Email" %>
      <%= f.password_field :password, :placeholder => "Password" %>
      <%= f.submit "Create an account", class: "btn-submit" %>
    <% end %>

  
    </div>
  </div>
</div>